whiteList:
  - pbxproj
  - vyacheslav
  - subspecs
  - xcscheme
  - usleep
  - xcbeautify
  - github
  - thii
  - associatedtype
  - rethrows
  - recursively
  - appex
  - xcschemes
  - xcuserdatad
  - xcuserdata
  - xcshareddata
  - lhs
  - stderror
  - anyarray
  - localized
  - kareman
  - autoreleasepool
  - tput
  - boolable
  - nsrange
  - xcodebuild
  - sdk
  - podfile
  - xcodeproj
  - yml
  - swiftlint
  - ykkd
  - iphoneos
  - ios
  - iphonesimulator
  - codable
  - xcworkspace
  - sysctl
  - machdep
  - dirs
  - xcconfig
  - xcargs
  - wholemodule
  - couldn
  - xcframeworks
  - alamofire
  - doesn
  - xcodegen
  - swiftyfinch
  - serialization
  - isystem
  - githubusercontent
  - img
  - khorkov
  - proj
  - deintegrate
  - rhs
  - colton
  - schlosser
  - parallelization
  - iframework
  - fd
  - ecf
  - bcfeef
  - mlch
  - utsname
  - uname
  - cocoapods
  - leavez
  - amazonaws
  - realized
  - fbadge
  - ftype
  - dswift
  - swifty
  - swiftish
  - fpackages
  - fapi
  - fswiftpackageindex
  - swiftpackageindex
  - didn
  - optimizations
  - clt
  - nexport
  - zshrc
  - zshenv
  - th
  - finalized
  - fswiftyfinch
  - dplatforms
  - svg
  - yandex
  - fff
  - faq
  - standardized
  - shwifty
  - utf
